config/routes.rb
HouddPre::Application.routes.draw do

  resources :medium_trials

  resources :medium_mission_invs

  resources :medium_missions

  resources :medium_mission_strategies

  match '/medium_item_equip_invs/select_body_parts'
  match '/medium_item_equip_invs/:id/select_body_parts' => 'medium_item_equip_invs#select_body_parts'
  match '/medium_item_equip_invs/select_items'
  match '/medium_item_equip_invs/:id/select_items' => 'medium_item_equip_invs#select_items'
  resources :medium_item_equip_invs

  resources :medium_skill_exp_invs

  resources :medium_skills

  resources :medium_specie_job_invs

  resources :medium_squads

  resources :medium_genes

  resources :medium_mobs

  resources :medium_jobs

  resources :medium_body_part_invs

  resources :medium_species

  resources :medium_families

  resources :medium_items

  resources :medium_research_allotments

  resources :medium_item_infos

  resources :medium_status_mods

  resources :medium_atk_infos

  resources :medium_body_parts

  match '/medium_dungeon_cells/:id/select_id' => 'medium_dungeon_cells#select_id'
  resources :medium_dungeon_cells

  resources :medium_resources

  resources :medium_terrains

  match '/medium_map_cells/:id/select_id' => 'medium_map_cells#select_id'
  resources :medium_map_cells

  resources :medium_tc_item_invs

  resources :medium_const_nec_res_invs

  resources :medium_constructions

  resources :medium_dungeons

  resources :medium_maps

  resources :medium_symbol_lists

  resources :medium_roads

  match '/medium_houdd_users/:id/proceed_research' => 'medium_houdd_users#proceed_research'
  match '/medium_houdd_users/:id/proceed_item_manufacture' => 'medium_houdd_users#proceed_item_manufacture'
  match '/medium_houdd_users/:id/proceed_construction' => 'medium_houdd_users#proceed_construction'
  match '/medium_houdd_users/:id/select_mapcell_id' => 'medium_houdd_users#select_mapcell_id'
  match '/medium_houdd_users/:id/select_map_id' => 'medium_houdd_users#select_map_id'
  match '/medium_houdd_users/:id/select_map_id2' => 'medium_houdd_users#select_map_id2'
  match '/medium_houdd_users/:id/select_dungeon_id' => 'medium_houdd_users#select_dungeon_id'
  match '/medium_houdd_users/:id/select_dungeoncell/:dungeon_id/:x/:y' => 'medium_houdd_users#select_dungeoncell_id'
  match '/medium_houdd_users/:id/select_items' => 'medium_houdd_users#select_items'
  match '/medium_houdd_users/:id/select_mobs' => 'medium_houdd_users#select_mobs'
  match '/medium_houdd_users/:id/select_mob_status' => 'medium_houdd_users#select_mob_status'
  match '/medium_houdd_users/:id/select_mob_skills' => 'medium_houdd_users#select_mob_skills'
  match '/medium_houdd_users/:id/select_mob_equips' => 'medium_houdd_users#select_mob_equips'
  match '/medium_houdd_users/:id/select_mob_mates' => 'medium_houdd_users#select_mob_mates'
  match '/medium_houdd_users/:id/select_iteminfo_id' => 'medium_houdd_users#select_iteminfo_id', as: 'select_iteminfo_id_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/add_strategy' => 'medium_houdd_users#add_strategy'
  match '/medium_houdd_users/:id/edit_strategy' => 'medium_houdd_users#edit_strategy'
  match '/medium_houdd_users/:id/update_strategy' => 'medium_houdd_users#update_strategy', :via => :post
  match '/medium_houdd_users/delete_strategy/:strategy_id' => 'medium_houdd_users#delete_strategy', :via => :delete
  match '/medium_houdd_users/:id/add_mission' => 'medium_houdd_users#add_mission'
  match '/medium_houdd_users/:id/edit_mission' => 'medium_houdd_users#edit_mission'
  match '/medium_houdd_users/:id/update_mission' => 'medium_houdd_users#update_mission', :via => :post
  match '/medium_houdd_users/delete_mission/:mission_id' => 'medium_houdd_users#delete_mission', :via => :delete
  match '/medium_houdd_users/:id/add_squad' => 'medium_houdd_users#add_squad'
  match '/medium_houdd_users/:id/edit_squad' => 'medium_houdd_users#edit_squad'
  match '/medium_houdd_users/:id/update_squad' => 'medium_houdd_users#update_squad', :via => :post
  match '/medium_houdd_users/:id/update_dungeon_squad/:dungeon_id/:x/:y' => 'medium_houdd_users#update_dungeon_squad', :via => :put
  match '/medium_houdd_users/:id/update_dungeon_trap/:dungeon_id/:x/:y' => 'medium_houdd_users#update_dungeon_trap', :via => :put
  match '/medium_houdd_users/delete_squad/:squad_id' => 'medium_houdd_users#delete_squad', :via => :delete
  match '/medium_houdd_users/:id/add_random_mob' => 'medium_houdd_users#add_random_mob'
  match '/medium_houdd_users/:id/create_random_user_mob' => 'medium_houdd_users#create_random_user_mob', :via => :post
  match '/medium_houdd_users/:id/create_mated_user_mob' => 'medium_houdd_users#create_mated_user_mob', :via => :post
  match '/medium_houdd_users/:id/all_mobs_auto_equip' => 'medium_houdd_users#all_mobs_auto_equip', :via => :put
  match '/medium_houdd_users/:id/add_random_gene' => 'medium_houdd_users#add_random_gene'
  match '/medium_houdd_users/:id/add_item_que' => 'medium_houdd_users#add_item_que'
  match '/medium_houdd_users/:id/delete_item_que' => 'medium_houdd_users#delete_item_que'
  match '/medium_houdd_users/:id/update_research' => 'medium_houdd_users#update_research'
  match '/medium_houdd_users/:id/update_mob_equips' => 'medium_houdd_users#update_mob_equips', :via => :post
  match '/medium_houdd_users/:id/update_construction' => 'medium_houdd_users#update_construction'
  match '/medium_houdd_users/:id/update_allotments' => 'medium_houdd_users#update_allotments', as: 'update_allotments_medium_houdd_user', :via => :put
  match '/medium_houdd_users/:id/admin_mob' => 'medium_houdd_users#admin_mob', as: 'admin_mob_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/admin_master' => 'medium_houdd_users#admin_master', as: 'admin_master_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/admin_top' => 'medium_houdd_users#admin_top', as: 'admin_top_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_strategy' => 'medium_houdd_users#mypage_strategy', as: 'mypage_strategy_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/:trial_turn_index/:battle_turn_index/view_battle_log' => 'medium_houdd_users#view_battle_log'
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/:trial_turn_index/view_trial_log' => 'medium_houdd_users#view_trial_log'
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/draw_dungeon_cell' => 'medium_houdd_users#draw_dungeon_cell'
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/mission_log' => 'medium_houdd_users#mypage_mission_log', as: 'mypage_mission_log_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_mission' => 'medium_houdd_users#mypage_mission', as: 'mypage_mission_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_mob' => 'medium_houdd_users#mypage_mob', as: 'mypage_mob_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_item' => 'medium_houdd_users#mypage_item', as: 'mypage_item_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_manufacture' => 'medium_houdd_users#mypage_manufacture', as: 'mypage_manufacture_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_research' => 'medium_houdd_users#mypage_research', as: 'mypage_research_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_territory' => 'medium_houdd_users#mypage_territory', as: 'mypage_territory_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_dungeon' => 'medium_houdd_users#mypage_dungeon', as: 'mypage_dungeon_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_top' => 'medium_houdd_users#mypage_top', as: 'mypage_top_medium_houdd_user', :via => :get
  resources :medium_houdd_users

  match '/mostsmalltrials/:id/log' => 'mostsmalltrials#log', as: 'log_mostsmalltrial', :via => :get
  match '/mostsmalltrials/:id/check_battlelog' => 'mostsmalltrials#check_battlelog'
  match '/mostsmalltrials/:id/check_battleset' => 'mostsmalltrials#check_battleset'
  match '/mostsmalltrials/:id/check_log' => 'mostsmalltrials#check_log'
  match '/mostsmalltrials/select_missions'
  match '/mostsmalltrials/:id/select_missions' => 'mostsmalltrials#select_missions'
  resources :mostsmalltrials

  resources :mostsmallmissioninventories

  resources :mostsmallmissions

  resources :mostsmallstrategies

  resources :mostsmallmissioncategories

  resources :mostsmalltreasureitems

  resources :mostsmalltrapeffectinventories

  resources :mostsmalltrapinfos

  resources :mostsmallskilleffectinventories

  resources :mostsmallskills

  match '/mostsmalltreasurechests/select_dungeontxt'
  match '/mostsmalltreasurechests/:id/select_dungeontxt' => 'mostsmalltreasurechests#select_dungeontxt'
  resources :mostsmalltreasurechests

  resources :mostsmallmobspecies

  resources :mostsmallitemequipinventories

  match '/mostsmallmobs/set_default_value'
  match '/mostsmallmobs/:id/set_default_value' => 'mostsmallmobs#set_default_value'
  resources :mostsmallmobs

  resources :mostsmallsquads

  match '/mostsmallmobgenes/set_default_value'
  match '/mostsmallmobgenes/:id/set_default_value' => 'mostsmallmobgenes#set_default_value'
  resources :mostsmallmobgenes
  
  match '/mostsmallitems/set_default_value'
  match '/mostsmallitems/:id/set_default_value' => 'mostsmallitems#set_default_value'
  resources :mostsmallitems

  resources :mostsmallitemeffectinventories

  resources :mostsmalliteminfos

  resources :mostsmallitemcategories

  resources :mostsmallskillcategories

  resources :mostsmallspeciejobinventories

  resources :mostsmalljobs

  resources :mostsmalleffects

  resources :mostsmallequipslotinventories

  resources :mostsmallequipslots

  resources :mostsmallresearches

  resources :mostsmallroads

  resources :mostsmallconstproducts

  resources :mostsmallterrainproducts

  resources :mostsmallterrains

  resources :mostsmallresources

  resources :mostsmallelements

app/models/medium_gene.rb
class MediumGene < ActiveRecord::Base
  belongs_to :medium_specie
end

app/controllers/medium_genes_controller.rb
class MediumGenesController < ApplicationController
  # GET /medium_genes
  # GET /medium_genes.json
  def index
    @medium_genes = MediumGene.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medium_genes }
    end
  end

  # GET /medium_genes/1
  # GET /medium_genes/1.json
  def show
    @medium_gene = MediumGene.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medium_gene }
    end
  end

  # GET /medium_genes/new
  # GET /medium_genes/new.json
  def new
    @medium_gene = MediumGene.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medium_gene }
    end
  end

  # GET /medium_genes/1/edit
  def edit
    @medium_gene = MediumGene.find(params[:id])
  end

  # POST /medium_genes
  # POST /medium_genes.json
  def create
    @medium_gene = MediumGene.new(params[:medium_gene])

    respond_to do |format|
      if @medium_gene.save
        format.html { redirect_to @medium_gene, notice: 'Medium gene was successfully created.' }
        format.json { render json: @medium_gene, status: :created, location: @medium_gene }
      else
        format.html { render action: "new" }
        format.json { render json: @medium_gene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medium_genes/1
  # PUT /medium_genes/1.json
  def update
    @medium_gene = MediumGene.find(params[:id])

    respond_to do |format|
      if @medium_gene.update_attributes(params[:medium_gene])
        format.html { redirect_to @medium_gene, notice: 'Medium gene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medium_gene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medium_genes/1
  # DELETE /medium_genes/1.json
  def destroy
    @medium_gene = MediumGene.find(params[:id])
    @medium_gene.destroy

    respond_to do |format|
      format.html { redirect_to medium_genes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/medium_genes_helper.rb
module MediumGenesHelper
end

app/views/medium_genes/_form.html.erb
<%= form_for(@medium_gene) do |f| %>
  <% if @medium_gene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medium_gene.errors.count, "error") %> prohibited this medium_gene from being saved:</h2>

      <ul>
      <% @medium_gene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :medium_specie %><br />
    <%= f.collection_select(:medium_specie_id, MediumSpecie.find(:all), :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :dominance_flg %><br />
    <%= f.check_box :dominance_flg %>
  </div>
  <div class="field">
    <%= f.label :prolificacy_mod %><br />
    <%= f.text_field :prolificacy_mod %>
  </div>
  <div class="field">
    <%= f.label :longevity_mod %><br />
    <%= f.text_field :longevity_mod %>
  </div>
  <div class="field">
    <%= f.label :growth_mod %><br />
    <%= f.text_field :growth_mod %>
  </div>
  <div class="field">
    <%= f.label :cost_mod %><br />
    <%= f.text_field :cost_mod %>
  </div>
  <div class="field">
    <%= f.label :str_mod %><br />
    <%= f.text_field :str_mod %>
  </div>
  <div class="field">
    <%= f.label :dex_mod %><br />
    <%= f.text_field :dex_mod %>
  </div>
  <div class="field">
    <%= f.label :con_mod %><br />
    <%= f.text_field :con_mod %>
  </div>
  <div class="field">
    <%= f.label :int_mod %><br />
    <%= f.text_field :int_mod %>
  </div>
  <div class="field">
    <%= f.label :wis_mod %><br />
    <%= f.text_field :wis_mod %>
  </div>
  <div class="field">
    <%= f.label :cha_mod %><br />
    <%= f.text_field :cha_mod %>
  </div>
  <div class="field">
    <%= f.label :phys_def_mod %><br />
    <%= f.text_field :phys_def_mod %>
  </div>
  <div class="field">
    <%= f.label :skill_def_mod %><br />
    <%= f.text_field :skill_def_mod %>
  </div>
  <div class="field">
    <%= f.label :ele_fw_mod %><br />
    <%= f.text_field :ele_fw_mod %>
  </div>
  <div class="field">
    <%= f.label :ele_ld_mod %><br />
    <%= f.text_field :ele_ld_mod %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medium_genes/edit.html.erb
<h1>Editing medium_gene</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium_gene %> |
<%= link_to 'Back', medium_genes_path %>

app/views/medium_genes/index.html.erb
<h1>Listing medium_genes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Specie</th>
    <th>Domi-flg</th>
    <th>Prolificacy</th>
    <th>Longevity</th>
    <th>Growth</th>
    <th>Cost</th>
    <th>Str</th>
    <th>Dex</th>
    <th>Con</th>
    <th>Int</th>
    <th>Wis</th>
    <th>Cha</th>
    <th>P-def</th>
    <th>S-def</th>
    <th>Ele-fw</th>
    <th>Ele-ld</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @medium_genes.each do |medium_gene| %>
  <tr>
    <td><%= medium_gene.name %></td>
    <td><%= medium_gene.medium_specie.name unless medium_gene.medium_specie.blank? %></td>
    <td><%= medium_gene.dominance_flg %></td>
    <td><%= medium_gene.prolificacy_mod %></td>
    <td><%= medium_gene.longevity_mod %></td>
    <td><%= medium_gene.growth_mod %></td>
    <td><%= medium_gene.cost_mod %></td>
    <td><%= medium_gene.str_mod %></td>
    <td><%= medium_gene.dex_mod %></td>
    <td><%= medium_gene.con_mod %></td>
    <td><%= medium_gene.int_mod %></td>
    <td><%= medium_gene.wis_mod %></td>
    <td><%= medium_gene.cha_mod %></td>
    <td><%= medium_gene.phys_def_mod %></td>
    <td><%= medium_gene.skill_def_mod %></td>
    <td><%= medium_gene.ele_fw_mod %></td>
    <td><%= medium_gene.ele_ld_mod %></td>
    <td><%= link_to 'Show', medium_gene %></td>
    <td><%= link_to 'Edit', edit_medium_gene_path(medium_gene) %></td>
    <td><%= link_to 'Destroy', medium_gene, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medium gene', new_medium_gene_path %>

app/views/medium_genes/new.html.erb
<h1>New medium_gene</h1>

<%= render 'form' %>

<%= link_to 'Back', medium_genes_path %>

app/views/medium_genes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @medium_gene.name %>
</p>

<p>
  <b>Medium specie:</b>
  <%= @medium_gene.medium_specie.name unless @medium_gene.medium_specie.blank? %>
</p>

<p>
  <b>Dominance flg:</b>
  <%= @medium_gene.dominance_flg %>
</p>

<p>
  <b>Prolificacy mod:</b>
  <%= @medium_gene.prolificacy_mod %>
</p>

<p>
  <b>Longevity mod:</b>
  <%= @medium_gene.longevity_mod %>
</p>

<p>
  <b>Growth mod:</b>
  <%= @medium_gene.growth_mod %>
</p>

<p>
  <b>Cost mod:</b>
  <%= @medium_gene.cost_mod %>
</p>

<p>
  <b>Str mod:</b>
  <%= @medium_gene.str_mod %>
</p>

<p>
  <b>Dex mod:</b>
  <%= @medium_gene.dex_mod %>
</p>

<p>
  <b>Con mod:</b>
  <%= @medium_gene.con_mod %>
</p>

<p>
  <b>Int mod:</b>
  <%= @medium_gene.int_mod %>
</p>

<p>
  <b>Wis mod:</b>
  <%= @medium_gene.wis_mod %>
</p>

<p>
  <b>Cha mod:</b>
  <%= @medium_gene.cha_mod %>
</p>

<p>
  <b>Phys def mod:</b>
  <%= @medium_gene.phys_def_mod %>
</p>

<p>
  <b>Skill def mod:</b>
  <%= @medium_gene.skill_def_mod %>
</p>

<p>
  <b>Ele fw mod:</b>
  <%= @medium_gene.ele_fw_mod %>
</p>

<p>
  <b>Ele ld mod:</b>
  <%= @medium_gene.ele_ld_mod %>
</p>


<%= link_to 'Edit', edit_medium_gene_path(@medium_gene) %> |
<%= link_to 'Back', medium_genes_path %>