config/routes.rb
  match '/medium_houdd_users/:id/create_random_user_mob' => 'medium_houdd_users#create_random_user_mob', :via => :post
  match '/medium_houdd_users/:id/create_mated_user_mob' => 'medium_houdd_users#create_mated_user_mob', :via => :post
  match '/medium_houdd_users/:id/all_mobs_auto_equip' => 'medium_houdd_users#all_mobs_auto_equip', :via => :put
  match '/medium_houdd_users/:id/add_random_gene' => 'medium_houdd_users#add_random_gene'
  match '/medium_houdd_users/:id/add_item_que' => 'medium_houdd_users#add_item_que'
  match '/medium_houdd_users/:id/delete_item_que' => 'medium_houdd_users#delete_item_que'
  match '/medium_houdd_users/:id/update_research' => 'medium_houdd_users#update_research'
  match '/medium_houdd_users/:id/update_mob_equips' => 'medium_houdd_users#update_mob_equips', :via => :post
  match '/medium_houdd_users/:id/update_construction' => 'medium_houdd_users#update_construction'
  match '/medium_houdd_users/:id/update_allotments' => 'medium_houdd_users#update_allotments', as: 'update_allotments_medium_houdd_user', :via => :put
  match '/medium_houdd_users/:id/admin_mob' => 'medium_houdd_users#admin_mob', as: 'admin_mob_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/admin_master' => 'medium_houdd_users#admin_master', as: 'admin_master_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/admin_top' => 'medium_houdd_users#admin_top', as: 'admin_top_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_strategy' => 'medium_houdd_users#mypage_strategy', as: 'mypage_strategy_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/:trial_turn_index/:battle_turn_index/view_battle_log' => 'medium_houdd_users#view_battle_log'
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/:trial_turn_index/view_trial_log' => 'medium_houdd_users#view_trial_log'
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/draw_dungeon_cell' => 'medium_houdd_users#draw_dungeon_cell'
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/mission_log' => 'medium_houdd_users#mypage_mission_log', as: 'mypage_mission_log_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_mission' => 'medium_houdd_users#mypage_mission', as: 'mypage_mission_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_mob' => 'medium_houdd_users#mypage_mob', as: 'mypage_mob_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_item' => 'medium_houdd_users#mypage_item', as: 'mypage_item_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_manufacture' => 'medium_houdd_users#mypage_manufacture', as: 'mypage_manufacture_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_research' => 'medium_houdd_users#mypage_research', as: 'mypage_research_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_territory' => 'medium_houdd_users#mypage_territory', as: 'mypage_territory_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_dungeon' => 'medium_houdd_users#mypage_dungeon', as: 'mypage_dungeon_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_top' => 'medium_houdd_users#mypage_top', as: 'mypage_top_medium_houdd_user', :via => :get
  resources :medium_houdd_users

  match '/mostsmalltrials/:id/log' => 'mostsmalltrials#log', as: 'log_mostsmalltrial', :via => :get
  match '/mostsmalltrials/:id/check_battlelog' => 'mostsmalltrials#check_battlelog'
  match '/mostsmalltrials/:id/check_battleset' => 'mostsmalltrials#check_battleset'
  match '/mostsmalltrials/:id/check_log' => 'mostsmalltrials#check_log'
  match '/mostsmalltrials/select_missions'
  match '/mostsmalltrials/:id/select_missions' => 'mostsmalltrials#select_missions'
  resources :mostsmalltrials

  resources :mostsmallmissioninventories

  resources :mostsmallmissions

  resources :mostsmallstrategies

  resources :mostsmallmissioncategories

  resources :mostsmalltreasureitems

  resources :mostsmalltrapeffectinventories

  resources :mostsmalltrapinfos

  resources :mostsmallskilleffectinventories

  resources :mostsmallskills

  match '/mostsmalltreasurechests/select_dungeontxt'
  match '/mostsmalltreasurechests/:id/select_dungeontxt' => 'mostsmalltreasurechests#select_dungeontxt'
  resources :mostsmalltreasurechests

  resources :mostsmallmobspecies

  resources :mostsmallitemequipinventories

  match '/mostsmallmobs/set_default_value'
  match '/mostsmallmobs/:id/set_default_value' => 'mostsmallmobs#set_default_value'
  resources :mostsmallmobs

  resources :mostsmallsquads

  match '/mostsmallmobgenes/set_default_value'
  match '/mostsmallmobgenes/:id/set_default_value' => 'mostsmallmobgenes#set_default_value'
  resources :mostsmallmobgenes
  
  match '/mostsmallitems/set_default_value'
  match '/mostsmallitems/:id/set_default_value' => 'mostsmallitems#set_default_value'
  resources :mostsmallitems

  resources :mostsmallitemeffectinventories

  resources :mostsmalliteminfos

  resources :mostsmallitemcategories

  resources :mostsmallskillcategories

  resources :mostsmallspeciejobinventories

  resources :mostsmalljobs

  resources :mostsmalleffects

  resources :mostsmallequipslotinventories

  resources :mostsmallequipslots

  resources :mostsmallresearches

  resources :mostsmallroads

  resources :mostsmallconstproducts

  resources :mostsmallterrainproducts

  resources :mostsmallterrains

  resources :mostsmallresources

  resources :mostsmallelements

  match '/mostsmalltraps/select_dungeontxt'
  match '/mostsmalltraps/:id/select_dungeontxt' => 'mostsmalltraps#select_dungeontxt'
  resources :mostsmalltraps

  match '/mostsmallconstructions/select_maptxt'
  match '/mostsmallconstructions/:id/select_maptxt' => 'mostsmallconstructions#select_maptxt'
  resources :mostsmallconstructions

  resources :mostsmallconstructioninfos

  resources :mostsmallconstructionfamilies

  match '/mostsmallterritories/random_map_txt'
  match '/mostsmallterritories/:id/dungeon_edit' => 'mostsmallterritories#dungeon_edit', as: 'dungeon_edit_mostsmallterritories', :via => :get
  resources :mostsmallterritories

  match '/mostsmallusers/:id/mypage' => 'mostsmallusers#mypage', as: 'mypage_mostsmalluser', :via => :get
  resources :mostsmallusers

  match '/moresmalltrials/:id/log' => 'moresmalltrials#log', as: 'log_moresmalltrial', :via => :get
  match '/moresmalltrials/:id/execute' => 'moresmalltrials#execute'
  match '/moresmalltrials/:id/check_battlelog' => 'moresmalltrials#check_battlelog'
  match '/moresmalltrials/:id/check_log' => 'moresmalltrials#check_log'
  match '/moresmalltrials/select_mobunits'
  match '/moresmalltrials/:id/select_mobunits' => 'moresmalltrials#select_mobunits'
  resources :moresmalltrials

  resources :moresmalltrialstatuses

  match '/moresmalltops/:id/portal' => 'moresmalltops#portal', as: 'portal_moresmalltops', :via => :get
  resources :moresmalltops

  match '/moresmallmobs/select_squad'
  match '/moresmallmobs/:id/select_squad' => 'moresmallmobs#select_squad'
  resources :moresmallmobs

  match '/moresmallmobsquads/select_mob_and_unit'
  match '/moresmallmobsquads/:id/select_mob_and_unit' => 'moresmallmobsquads#select_mob_and_unit'
  resources :moresmallmobsquads

  match '/moresmallmobunits/select_cur_map'
  match '/moresmallmobunits/:id/select_cur_map' => 'moresmallmobunits#select_cur_map'
  match '/moresmallmobunits/select_squad'
  match '/moresmallmobunits/:id/select_squad' => 'moresmallmobunits#select_squad'
  resources :moresmallmobunits

  resources :moresmallstrategies

  resources :moresmallweponinfos

  resources :moresmallarmorinfos

  resources :moresmallmagicinfos

  resources :moresmallmobinfos

  resources :moresmallmaps

  resources :moresmallusers

  match '/smalltrials/:id/log' => 'smalltrials#log', as: 'log_smalltrial', :via => :get
  match '/smalltrials/:id/execute' => 'smalltrials#execute'
  match '/smalltrials/:id/check_log' => 'smalltrials#check_log'
  match '/smalltrials/select_mobunits'
  match '/smalltrials/:id/select_mobunits' => 'smalltrials#select_mobunits'
  resources :smalltrials

  resources :smalltrialstatuses

  match '/smallmobunits/select_map'
  match '/smallmobunits/:id/select_map' => 'smallmobunits#select_map'
  match '/smallmobunits/select_squad'
  match '/smallmobunits/:id/select_squad' => 'smallmobunits#select_squad'
  resources :smallmobunits

  match '/smallmobsquads/select_mob_and_unit'
  match '/smallmobsquads/:id/select_mob_and_unit' => 'smallmobsquads#select_mob_and_unit'
  resources :smallmobsquads

  resources :smallstrategies

  match '/smalltops/:id/portal' => 'smalltops#portal', as: 'portal_smalltops', :via => :get
  resources :smalltops

  resources :smallweponinfos

  resources :smallarmorinfos

  match '/smallmobs/select_squad'
  match '/smallmobs/:id/select_squad' => 'smallmobs#select_squad'
  resources :smallmobs

  resources :smallmagicinfos

  resources :smallmobinfos

  resources :smallmaps

  resources :smallusers

  resources :mosttinymobtrails

  resources :mosttinybattles

  resources :mosttinystrategies

  resources :mosttinymobsetups

  resources :mosttinymobs

  resources :mosttinymobinfos

  resources :mosttinymaps

  resources :mosttinyturns

  match '/mosttinytrials/select_map_and_def_mobs'
  match '/mosttinytrials/:id/select_map_and_def_mobs' => 'mosttinytrials#select_map_and_def_mobs'
  match '/mosttinytrials/select_atk_mobs'
  match '/mosttinytrials/:id/select_atk_mobs' => 'mosttinytrials#select_atk_mobs'
  match '/mosttinytrials/:id/start' => 'mosttinytrials#start', as: 'start_mosttinytrial', :via => :get
  match '/mosttinytrials/:id/execute' => 'mosttinytrials#execute'
  match '/mosttinytrials/:id/check_log' => 'mosttinytrials#check_log'
  resources :mosttinytrials

  resources :mosttinyusers

  resources :moretinymobbattles

  resources :moretinymobtrails

  resources :moretinymobs

  resources :moretinymobinfos

  resources :moretinymaps

app/models/mosttinytrial.rb
class Mosttinytrial < ActiveRecord::Base
  
  has_many :mosttinymobsetups
  accepts_nested_attributes_for :mosttinymobsetups

  belongs_to :def_user, :class_name => 'Mosttinyuser', :foreign_key => 'def_user_id'
  belongs_to :atk_user, :class_name => 'Mosttinyuser', :foreign_key => 'atk_user_id'
  belongs_to :def_strategy, :class_name => 'Mosttinystrategy', :foreign_key => 'def_strategy_id'
  belongs_to :atk_strategy, :class_name => 'Mosttinystrategy', :foreign_key => 'atk_strategy_id'
  belongs_to :map, :class_name => 'Mosttinymap', :foreign_key => 'map_id'
  
  def def_bench_mob_ids
    @def_mob_ids || mosttinymobsetups.collect{|p| p.id}
  end
 
  def def_bench_mob_ids=(id_array)
    @def_mob_ids = id_array.collect{|id| id.to_i};
  end
  
  def def_setup_mob_ids
    @def_mob_ids || mosttinymobsetups.collect{|p| p.id}
  end
 
  def def_setup_mob_ids=(id_array)
    @def_mob_ids = id_array.collect{|id| id.to_i};
  end
  
  def def_setup_mob_ids_and_names_by_user(user_id)
    Mosttinymobsetup.find_all_by_mosttinytrial_id(id, :include => :mosttinymob, :conditions => ["mosttinymobs.mosttinyuser_id = ?", user_id]).map{ |def_setup_mob| [def_setup_mob.mosttinymob.name, def_setup_mob.mosttinymob.id] }
  end

  def def_bench_mob_ids_and_names_by_user(user_id)
    all_mobs = Mosttinymob.find_all_by_mosttinyuser_id(user_id).map{ |def_bench_mob| [def_bench_mob.name, def_bench_mob.id] }
    setup_mobs = Mosttinymobsetup.find_all_by_mosttinytrial_id(id, :include => :mosttinymob, :conditions => ["mosttinymobs.mosttinyuser_id = ?", user_id]).map{ |def_setup_mob| [def_setup_mob.mosttinymob.name, def_setup_mob.mosttinymob.id] }
    all_mobs - setup_mobs 
  end

  def atk_bench_mob_ids
    @atk_mob_ids || mosttinymobsetups.collect{|p| p.id}
  end
 
  def atk_bench_mob_ids=(id_array)
    @atk_mob_ids = id_array.collect{|id| id.to_i};
  end
  
  def atk_setup_mob_ids
    @atk_mob_ids || mosttinymobsetups.collect{|p| p.id}
  end
 
  def atk_setup_mob_ids=(id_array)
    @atk_mob_ids = id_array.collect{|id| id.to_i};
  end
  after_save :assign_setup_mobs

  def assign_setup_mobs
    
    map = Mosttinymap.find(map_id)
 
    2.times do |i|
      
      if i == 0
        mob_ids = @def_mob_ids
        is_guard = true
      elsif i == 1
        mob_ids = @atk_mob_ids
        is_guard = false
      end

      if mob_ids
        new_ids = mob_ids
        old_ids = Mosttinymobsetup.find_all_by_mosttinytrial_id_and_is_guard(id, is_guard).collect{|m| m.mosttinymob_id}
        ids_to_delete = old_ids - (old_ids & new_ids)
        ids_to_add = new_ids - (old_ids & new_ids)
        mosttinytrial_id = id

        ids_to_delete.each do |mobsetup_id|
          Mosttinymobsetup.destroy_all(:mosttinytrial_id => mosttinytrial_id, :mosttinymob_id => mobsetup_id)
        end

        #start_points = Array.new
        ids_to_add.each do |mobsetup_id|
          unless mobsetup_id == 0
            start_point = map.random_unique_inside_point(is_guard)
            Mosttinymobsetup.create(:mosttinytrial_id => mosttinytrial_id, :mosttinymob_id => mobsetup_id, :is_guard => is_guard, :start_x => start_point['x'], :start_y => start_point['y'], :current_x => start_point['x'], :current_y => start_point['y'])
          end
        end
      end
    end
  end
end

app/controllers/mosttinytrials_controller.rb
class MosttinytrialsController < ApplicationController
  # GET /mosttinytrials
  # GET /mosttinytrials.json
  def index
    @mosttinytrials = Mosttinytrial.all(:include => [:def_user, :atk_user, :def_strategy, :atk_strategy, :map])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mosttinytrials }
    end
  end

  # GET /mosttinytrials/1
  # GET /mosttinytrials/1.json
  def show
    @mosttinytrial = Mosttinytrial.find(params[:id], :include => [:def_user, :atk_user, :def_strategy, :atk_strategy, :map])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mosttinytrial }
    end
  end

  # GET /mosttinytrials/new
  # GET /mosttinytrials/new.json
  def new
    @mosttinytrial = Mosttinytrial.new

    @gurad_mobs_size = Mosttinymob.find_all_by_mosttinyuser_id(2).size
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mosttinytrial }
    end
  end

  # GET /mosttinytrials/1/edit
  def edit
    @mosttinytrial = Mosttinytrial.find(params[:id])
  end

  # POST /mosttinytrials
  # POST /mosttinytrials.json
  def create
    @mosttinytrial = Mosttinytrial.new(params[:mosttinytrial])

    respond_to do |format|
      if @mosttinytrial.save
        format.html { redirect_to @mosttinytrial, notice: 'Mosttinytrial was successfully created.' }
        format.json { render json: @mosttinytrial, status: :created, location: @mosttinytrial }
      else
        format.html { render action: "new" }
        format.json { render json: @mosttinytrial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mosttinytrials/1
  # PUT /mosttinytrials/1.json
  def update
    @mosttinytrial = Mosttinytrial.find(params[:id])

    respond_to do |format|
      if @mosttinytrial.update_attributes(params[:mosttinytrial])
        format.html { redirect_to @mosttinytrial, notice: 'Mosttinytrial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mosttinytrial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mosttinytrials/1
  # DELETE /mosttinytrials/1.json
  def destroy
    @mosttinytrial = Mosttinytrial.find(params[:id])
    @mosttinytrial.destroy

    respond_to do |format|
      format.html { redirect_to mosttinytrials_url }
      format.json { head :no_content }
    end
  end
  # GET /mosttinytrials/select_map_and_def_mobs
  # GET /mosttinytrials/1/select_map_and_def_mobs
  def select_map_and_def_mobs
    @def_map = Mosttinymap.find_all_by_mosttinyuser_id(params[:def_user_id])
    @def_mob_size = Mosttinymob.find_all_by_mosttinyuser_id(params[:def_user_id]).size.to_s
    @def_bench_mob = Mosttinytrial.find(params[:id]).def_bench_mob_ids_and_names_by_user(params[:def_user_id])
    @def_setup_mob = Mosttinytrial.find(params[:id]).def_setup_mob_ids_and_names_by_user(params[:def_user_id])
    render
  end
  
  # GET /mosttinytrials/select_atk_mobs
  # GET /mosttinytrials/1/select_def_mobs
  def select_atk_mobs
    @atk_mob_size = Mosttinymob.find_all_by_mosttinyuser_id(params[:atk_user_id]).size
    @atk_bench_mob = Mosttinytrial.find(params[:id]).def_bench_mob_ids_and_names_by_user(params[:atk_user_id])
    @atk_setup_mob = Mosttinytrial.find(params[:id]).def_setup_mob_ids_and_names_by_user(params[:atk_user_id])
    render
  end
  
  # GET /mosttinytrials/1/start
  def start
    @mosttinytrial = Mosttinytrial.find(params[:id], :include => [:def_user, :atk_user, :def_strategy, :atk_strategy, :map, {:mosttinymobsetups => {:mosttinymob => :mosttinymobinfo}}])
  end

  # GET /mosttinytrials/1/execute
  def execute
    Mosttinyturncreator.create_all_by_id(params[:id])
    @max_turn = Mosttinyturn.find_all_by_mosttinytrial_id(params[:id]).size
    @current_turn = Mosttinyturn.find_all_by_mosttinytrial_id(params[:id], :include => [{:mosttinymobtrails => {:mosttinymobsetup => :mosttinymob}}, :mosttinybattles])[0]
    render
  end

  # GET /mosttinytrials/1/check_log
  def check_log
    turn_index = params[:turn].to_i - 1
    turn_index = 0 if turn_index < 0 
    @current_turn = Mosttinyturn.find_all_by_mosttinytrial_id(params[:id], :include => [{:mosttinymobtrails => {:mosttinymobsetup => :mosttinymob}}, :mosttinybattles])[turn_index]
    render
  end
end

app/helpers/mosttinytrials_helper.rb
module MosttinytrialsHelper
end

app/views/mosttinytrials/_form.html.erb
<%= form_for(@mosttinytrial) do |f| %>
  <% if @mosttinytrial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mosttinytrial.errors.count, "error") %> prohibited this mosttinytrial from being saved:</h2>

      <ul>
      <% @mosttinytrial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :def_user_id %><br />
    <%= f.collection_select(:def_user_id, Mosttinyuser.all, :id, :name, :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :def_strategy_id %><br />
    <%= f.collection_select(:def_strategy_id, Mosttinystrategy.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :map_id %><br />
    <%= render 'select_map', {:f => f} %>
  </div>
  <div class="field">
    <%= render 'select_def_mobs', {:f => f} %>
  </div>
  <div class="field">
    <%= f.label :atk_user_id %><br />
    <%= f.collection_select(:atk_user_id, Mosttinyuser.all, :id, :name, :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :atk_strategy_id %><br />
    <%= f.collection_select(:atk_strategy_id, Mosttinystrategy.all, :id, :name) %>
  </div>
  <div class="field">
    <%= render 'select_atk_mobs', {:f => f} %>
  </div>
  <div class="field">
    <%= f.label :is_completed %><br />
    <%= f.check_box :is_completed %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mosttinytrials/_redraw.js.erb
jQuery("#BattleLog").text("");
jQuery("#BattleLog").text("<%= escape_javascript(@current_turn.log) %>");

p = Processing.getInstanceById("MapCanvas")
p.draw();
RenderMap(jQuery('#MapText').val());

<% @current_turn.mosttinymobtrails.each do |mosttinymobtrail| %>
  p.renderMob(<%= mosttinymobtrail.from_x %>, <%= mosttinymobtrail.from_y %>, <%= mosttinymobtrail.mosttinymobsetup.is_guard %>, "<%= mosttinymobtrail.trail[0] %>");
<% unless mosttinymobtrail.trail.empty? %>
<% mosttinymobtrail.trailpoints.each do |trailpoint| %>
  p.renderTrail(<%= trailpoint["from_x"] %>, <%= trailpoint["from_y"] %>, <%= trailpoint["to_x"] %>, <%= trailpoint["to_y"] %>, <%= trailpoint["is_end"] %>, <%= mosttinymobtrail.mosttinymobsetup.is_guard %>);
<% end %>
<% end %>
<% end %>

<% @current_turn.mosttinybattles.each do |mosttinybattle| %>
  jQuery("#BattleLog").append("<%= escape_javascript(mosttinybattle.log) %>");
  jQuery("#hp_<%= mosttinybattle.tgt_mobsetup_id %>").text("<%= mosttinybattle.tgt_mob_current_hp %>");
<% if mosttinybattle.is_tgt_mob_dead %>
  p.renderDeadMob(<%= mosttinybattle.tgt_mob_x %>, <%= mosttinybattle.tgt_mob_y %>)
<% end %>
<% end %>

app/views/mosttinytrials/_select_atk_mobs.html.erb
# coding: utf-8
<div class="field">
    <table>
      <tr><td align="center">
        <%= f.label "Mobs in bench" %><br />
        <%= f.select(:atk_bench_mob_ids, {}, {}, {:multiple => true, :size => 3}) %>
      </td><td>
        <input id="btnMoveRightAtk" type="button" value="->" />  
        <br />  
        <input id="btnMoveLeftAtk" type="button" value="<-" />
      </td><td align="center">
        <%= f.label "Mobs in Setup" %><br />
        <%= f.select(:atk_setup_mob_ids, {}, {}, {:multiple => true, :size => 3}) %>
      </td></tr>
    </table>
</div>


app/views/mosttinytrials/_select_def_mobs.html.erb
# coding: utf-8
<div class="field">
    <table>
      <tr><td align="center">
        <%= f.label "Mobs in bench" %><br />
        <%= f.select(:def_bench_mob_ids, {}, {}, {:multiple => true, :size => 3}) %>
      </td><td>
        <input id="btnMoveRightDef" type="button" value="->" />  
        <br />  
        <input id="btnMoveLeftDef" type="button" value="<-" />
      </td><td align="center">
        <%= f.label "Mobs in Setup" %><br />
        <%= f.select(:def_setup_mob_ids, {}, {}, {:multiple => true, :size => 3}) %>
      </td></tr>
    </table>
</div>


app/views/mosttinytrials/_select_map.html.erb
# coding: utf-8
    <%= f.select(:map_id, [["ユーザーを選んで下さい。",0]]) %>

app/views/mosttinytrials/edit.html.erb
<h1>Editing mosttinytrial</h1>

<%= render 'form' %>

<%= link_to 'Show', @mosttinytrial %> |
<%= link_to 'Back', mosttinytrials_path %>

app/views/mosttinytrials/index.html.erb
<h1>Listing mosttinytrials</h1>

<table>
  <tr>
    <th>Def user</th>
    <th>Map</th>
    <th>Atk user</th>
    <th>is completed</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mosttinytrials.each do |mosttinytrial| %>
  <tr>
    <td><%= mosttinytrial.def_user.name %></td>
    <td><%= mosttinytrial.map.name %></td>
    <td><%= mosttinytrial.atk_user.name %></td>
    <td><%= mosttinytrial.is_completed %></td>
    <td><%= link_to 'Show', mosttinytrial %></td>
    <td><%= link_to 'Edit', edit_mosttinytrial_path(mosttinytrial) %></td>
    <td><%= link_to 'Destroy', mosttinytrial, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to 'Start', start_mosttinytrial_path(mosttinytrial) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mosttinytrial', new_mosttinytrial_path %>

app/views/mosttinytrials/new.html.erb
<h1>New mosttinytrial</h1>

<%= render 'form' %>

<%= link_to 'Back', mosttinytrials_path %>

app/views/mosttinytrials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Def user:</b>
  <%= @mosttinytrial.def_user.name %>
</p>

<p>
  <b>Def user strategy:</b>
  <%= @mosttinytrial.def_strategy.name %>
</p>

<p>
  <b>Map:</b>
  <%= @mosttinytrial.map.name %>
</p>

<p>
  <b>Atk user:</b>
  <%= @mosttinytrial.atk_user.name %>
</p>

<p>
  <b>Atk user strategy:</b>
  <%= @mosttinytrial.atk_strategy.name %>
</p>

<p>
  <b>is completed:</b>
  <%= @mosttinytrial.is_completed %>
</p>

<%= link_to 'Edit', edit_mosttinytrial_path(@mosttinytrial) %> |
<%= link_to 'Back', mosttinytrials_path %>