config/routes.rb
  match '/medium_houdd_users/:id/create_random_user_mob' => 'medium_houdd_users#create_random_user_mob', :via => :post
  match '/medium_houdd_users/:id/create_mated_user_mob' => 'medium_houdd_users#create_mated_user_mob', :via => :post
  match '/medium_houdd_users/:id/all_mobs_auto_equip' => 'medium_houdd_users#all_mobs_auto_equip', :via => :put
  match '/medium_houdd_users/:id/add_random_gene' => 'medium_houdd_users#add_random_gene'
  match '/medium_houdd_users/:id/add_item_que' => 'medium_houdd_users#add_item_que'
  match '/medium_houdd_users/:id/delete_item_que' => 'medium_houdd_users#delete_item_que'
  match '/medium_houdd_users/:id/update_research' => 'medium_houdd_users#update_research'
  match '/medium_houdd_users/:id/update_mob_equips' => 'medium_houdd_users#update_mob_equips', :via => :post
  match '/medium_houdd_users/:id/update_construction' => 'medium_houdd_users#update_construction'
  match '/medium_houdd_users/:id/update_allotments' => 'medium_houdd_users#update_allotments', as: 'update_allotments_medium_houdd_user', :via => :put
  match '/medium_houdd_users/:id/admin_mob' => 'medium_houdd_users#admin_mob', as: 'admin_mob_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/admin_master' => 'medium_houdd_users#admin_master', as: 'admin_master_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/admin_top' => 'medium_houdd_users#admin_top', as: 'admin_top_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_strategy' => 'medium_houdd_users#mypage_strategy', as: 'mypage_strategy_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/:trial_turn_index/:battle_turn_index/view_battle_log' => 'medium_houdd_users#view_battle_log'
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/:trial_turn_index/view_trial_log' => 'medium_houdd_users#view_trial_log'
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/draw_dungeon_cell' => 'medium_houdd_users#draw_dungeon_cell'
  match '/medium_houdd_users/:id/mypage_mission/:mission_id/mission_log' => 'medium_houdd_users#mypage_mission_log', as: 'mypage_mission_log_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_mission' => 'medium_houdd_users#mypage_mission', as: 'mypage_mission_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_mob' => 'medium_houdd_users#mypage_mob', as: 'mypage_mob_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_item' => 'medium_houdd_users#mypage_item', as: 'mypage_item_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_manufacture' => 'medium_houdd_users#mypage_manufacture', as: 'mypage_manufacture_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_research' => 'medium_houdd_users#mypage_research', as: 'mypage_research_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_territory' => 'medium_houdd_users#mypage_territory', as: 'mypage_territory_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_dungeon' => 'medium_houdd_users#mypage_dungeon', as: 'mypage_dungeon_medium_houdd_user', :via => :get
  match '/medium_houdd_users/:id/mypage_top' => 'medium_houdd_users#mypage_top', as: 'mypage_top_medium_houdd_user', :via => :get
  resources :medium_houdd_users

  match '/mostsmalltrials/:id/log' => 'mostsmalltrials#log', as: 'log_mostsmalltrial', :via => :get
  match '/mostsmalltrials/:id/check_battlelog' => 'mostsmalltrials#check_battlelog'
  match '/mostsmalltrials/:id/check_battleset' => 'mostsmalltrials#check_battleset'
  match '/mostsmalltrials/:id/check_log' => 'mostsmalltrials#check_log'
  match '/mostsmalltrials/select_missions'
  match '/mostsmalltrials/:id/select_missions' => 'mostsmalltrials#select_missions'
  resources :mostsmalltrials

  resources :mostsmallmissioninventories

  resources :mostsmallmissions

  resources :mostsmallstrategies

  resources :mostsmallmissioncategories

  resources :mostsmalltreasureitems

  resources :mostsmalltrapeffectinventories

  resources :mostsmalltrapinfos

  resources :mostsmallskilleffectinventories

  resources :mostsmallskills

  match '/mostsmalltreasurechests/select_dungeontxt'
  match '/mostsmalltreasurechests/:id/select_dungeontxt' => 'mostsmalltreasurechests#select_dungeontxt'
  resources :mostsmalltreasurechests

  resources :mostsmallmobspecies

  resources :mostsmallitemequipinventories

  match '/mostsmallmobs/set_default_value'
  match '/mostsmallmobs/:id/set_default_value' => 'mostsmallmobs#set_default_value'
  resources :mostsmallmobs

  resources :mostsmallsquads

  match '/mostsmallmobgenes/set_default_value'
  match '/mostsmallmobgenes/:id/set_default_value' => 'mostsmallmobgenes#set_default_value'
  resources :mostsmallmobgenes
  
  match '/mostsmallitems/set_default_value'
  match '/mostsmallitems/:id/set_default_value' => 'mostsmallitems#set_default_value'
  resources :mostsmallitems

  resources :mostsmallitemeffectinventories

  resources :mostsmalliteminfos

  resources :mostsmallitemcategories

  resources :mostsmallskillcategories

  resources :mostsmallspeciejobinventories

  resources :mostsmalljobs

  resources :mostsmalleffects

  resources :mostsmallequipslotinventories

  resources :mostsmallequipslots

  resources :mostsmallresearches

  resources :mostsmallroads

  resources :mostsmallconstproducts

  resources :mostsmallterrainproducts

  resources :mostsmallterrains

  resources :mostsmallresources

  resources :mostsmallelements

  match '/mostsmalltraps/select_dungeontxt'
  match '/mostsmalltraps/:id/select_dungeontxt' => 'mostsmalltraps#select_dungeontxt'
  resources :mostsmalltraps

  match '/mostsmallconstructions/select_maptxt'
  match '/mostsmallconstructions/:id/select_maptxt' => 'mostsmallconstructions#select_maptxt'
  resources :mostsmallconstructions

  resources :mostsmallconstructioninfos

  resources :mostsmallconstructionfamilies

  match '/mostsmallterritories/random_map_txt'
  match '/mostsmallterritories/:id/dungeon_edit' => 'mostsmallterritories#dungeon_edit', as: 'dungeon_edit_mostsmallterritories', :via => :get
  resources :mostsmallterritories

  match '/mostsmallusers/:id/mypage' => 'mostsmallusers#mypage', as: 'mypage_mostsmalluser', :via => :get
  resources :mostsmallusers

  match '/moresmalltrials/:id/log' => 'moresmalltrials#log', as: 'log_moresmalltrial', :via => :get
  match '/moresmalltrials/:id/execute' => 'moresmalltrials#execute'
  match '/moresmalltrials/:id/check_battlelog' => 'moresmalltrials#check_battlelog'
  match '/moresmalltrials/:id/check_log' => 'moresmalltrials#check_log'
  match '/moresmalltrials/select_mobunits'
  match '/moresmalltrials/:id/select_mobunits' => 'moresmalltrials#select_mobunits'
  resources :moresmalltrials

  resources :moresmalltrialstatuses

  match '/moresmalltops/:id/portal' => 'moresmalltops#portal', as: 'portal_moresmalltops', :via => :get
  resources :moresmalltops

  match '/moresmallmobs/select_squad'
  match '/moresmallmobs/:id/select_squad' => 'moresmallmobs#select_squad'
  resources :moresmallmobs

  match '/moresmallmobsquads/select_mob_and_unit'
  match '/moresmallmobsquads/:id/select_mob_and_unit' => 'moresmallmobsquads#select_mob_and_unit'
  resources :moresmallmobsquads

  match '/moresmallmobunits/select_cur_map'
  match '/moresmallmobunits/:id/select_cur_map' => 'moresmallmobunits#select_cur_map'
  match '/moresmallmobunits/select_squad'
  match '/moresmallmobunits/:id/select_squad' => 'moresmallmobunits#select_squad'
  resources :moresmallmobunits

  resources :moresmallstrategies

  resources :moresmallweponinfos

  resources :moresmallarmorinfos

  resources :moresmallmagicinfos

  resources :moresmallmobinfos

  resources :moresmallmaps

  resources :moresmallusers

  match '/smalltrials/:id/log' => 'smalltrials#log', as: 'log_smalltrial', :via => :get
  match '/smalltrials/:id/execute' => 'smalltrials#execute'
  match '/smalltrials/:id/check_log' => 'smalltrials#check_log'
  match '/smalltrials/select_mobunits'
  match '/smalltrials/:id/select_mobunits' => 'smalltrials#select_mobunits'
  resources :smalltrials

  resources :smalltrialstatuses

  match '/smallmobunits/select_map'
  match '/smallmobunits/:id/select_map' => 'smallmobunits#select_map'
  match '/smallmobunits/select_squad'
  match '/smallmobunits/:id/select_squad' => 'smallmobunits#select_squad'
  resources :smallmobunits

  match '/smallmobsquads/select_mob_and_unit'
  match '/smallmobsquads/:id/select_mob_and_unit' => 'smallmobsquads#select_mob_and_unit'
  resources :smallmobsquads

  resources :smallstrategies

  match '/smalltops/:id/portal' => 'smalltops#portal', as: 'portal_smalltops', :via => :get
  resources :smalltops

  resources :smallweponinfos

  resources :smallarmorinfos

  match '/smallmobs/select_squad'
  match '/smallmobs/:id/select_squad' => 'smallmobs#select_squad'
  resources :smallmobs

  resources :smallmagicinfos

  resources :smallmobinfos

  resources :smallmaps

  resources :smallusers

  resources :mosttinymobtrails

  resources :mosttinybattles

  resources :mosttinystrategies

  resources :mosttinymobsetups

  resources :mosttinymobs

  resources :mosttinymobinfos

  resources :mosttinymaps

  resources :mosttinyturns

  match '/mosttinytrials/select_map_and_def_mobs'
  match '/mosttinytrials/:id/select_map_and_def_mobs' => 'mosttinytrials#select_map_and_def_mobs'
  match '/mosttinytrials/select_atk_mobs'
  match '/mosttinytrials/:id/select_atk_mobs' => 'mosttinytrials#select_atk_mobs'
  match '/mosttinytrials/:id/start' => 'mosttinytrials#start', as: 'start_mosttinytrial', :via => :get
  match '/mosttinytrials/:id/execute' => 'mosttinytrials#execute'
  match '/mosttinytrials/:id/check_log' => 'mosttinytrials#check_log'
  resources :mosttinytrials

  resources :mosttinyusers

  resources :moretinymobbattles

  resources :moretinymobtrails

  resources :moretinymobs

  resources :moretinymobinfos

  resources :moretinymaps

app/models/mostsmallmobgene.rb
class Mostsmallmobgene < ActiveRecord::Base
  belongs_to :mostsmallmobspecie
  belongs_to :mothermobgene, :class_name => 'Mostsmallmobgene', :foreign_key => 'mothermobgene_id'
  belongs_to :fathermobgene, :class_name => 'Mostsmallmobgene', :foreign_key => 'fathermobgene_id'
  has_many :mostsmallmobs, :dependent => :delete_all
end

app/controllers/mostsmallmobgenes_controller.rb
class MostsmallmobgenesController < ApplicationController
  # GET /mostsmallmobgenes
  # GET /mostsmallmobgenes.json
  def index
    @mostsmallmobgenes = Mostsmallmobgene.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mostsmallmobgenes }
    end
  end

  # GET /mostsmallmobgenes/1
  # GET /mostsmallmobgenes/1.json
  def show
    @mostsmallmobgene = Mostsmallmobgene.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mostsmallmobgene }
    end
  end

  # GET /mostsmallmobgenes/new
  # GET /mostsmallmobgenes/new.json
  def new
    @mostsmallmobgene = Mostsmallmobgene.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mostsmallmobgene }
    end
  end

  # GET /mostsmallmobgenes/1/edit
  def edit
    @mostsmallmobgene = Mostsmallmobgene.find(params[:id])
  end

  # POST /mostsmallmobgenes
  # POST /mostsmallmobgenes.json
  def create
    @mostsmallmobgene = Mostsmallmobgene.new(params[:mostsmallmobgene])

    respond_to do |format|
      if @mostsmallmobgene.save
        format.html { redirect_to @mostsmallmobgene, notice: 'Mostsmallmobgene was successfully created.' }
        format.json { render json: @mostsmallmobgene, status: :created, location: @mostsmallmobgene }
      else
        format.html { render action: "new" }
        format.json { render json: @mostsmallmobgene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mostsmallmobgenes/1
  # PUT /mostsmallmobgenes/1.json
  def update
    @mostsmallmobgene = Mostsmallmobgene.find(params[:id])

    respond_to do |format|
      if @mostsmallmobgene.update_attributes(params[:mostsmallmobgene])
        format.html { redirect_to @mostsmallmobgene, notice: 'Mostsmallmobgene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mostsmallmobgene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mostsmallmobgenes/1
  # DELETE /mostsmallmobgenes/1.json
  def destroy
    @mostsmallmobgene = Mostsmallmobgene.find(params[:id])
    @mostsmallmobgene.destroy

    respond_to do |format|
      format.html { redirect_to mostsmallmobgenes_url }
      format.json { head :no_content }
    end
  end

  # GET /mostsmallmobgenes/set_default_value
  def set_default_value
    @mostsmallmobgene = Mostsmallmobgenecreator.create(params[:mobspecie_id], params[:mothergene_id], params[:fathergene_id])
  end
end

app/helpers/mostsmallmobgenes_helper.rb
module MostsmallmobgenesHelper
end

app/views/mostsmallmobgenes/_form.html.erb
<%= form_for(@mostsmallmobgene) do |f| %>
  <% if @mostsmallmobgene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mostsmallmobgene.errors.count, "error") %> prohibited this mostsmallmobgene from being saved:</h2>

      <ul>
      <% @mostsmallmobgene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mostsmallmobspecie %><br />
    <%= f.collection_select(:mostsmallmobspecie_id, Mostsmallmobspecie.find(:all), :id, :name) %>
    <input id="mostsmall_default_mobgene_value" type="button" value="デフォルト値" />
  </div>
  <div class="field">
    <%= f.label :mothermobgene_id %><br />
    <%= f.collection_select(:mothermobgene_id, Mostsmallmobgene.find(:all), :id, :name, :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :fathermobgene_id %><br />
    <%= f.collection_select(:fathermobgene_id, Mostsmallmobgene.find(:all), :id, :name, :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phys_mod %><br />
    <%= f.text_field :phys_mod %>
  </div>
  <div class="field">
    <%= f.label :int_mod %><br />
    <%= f.text_field :int_mod %>
  </div>
  <div class="field">
    <%= f.label :prolificacy_mod %><br />
    <%= f.text_field :prolificacy_mod %>
  </div>
  <div class="field">
    <%= f.label :longevity_mod %><br />
    <%= f.text_field :longevity_mod %>
  </div>
  <div class="field">
    <%= f.label :cost_mod %><br />
    <%= f.text_field :cost_mod %>
  </div>
  <div class="field">
    <%= f.label :growth_mod %><br />
    <%= f.text_field :growth_mod %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mostsmallmobgenes/edit.html.erb
<h1>Editing mostsmallmobgene</h1>

<%= render 'form' %>

<%= link_to 'Show', @mostsmallmobgene %> |
<%= link_to 'Back', mostsmallmobgenes_path %>

app/views/mostsmallmobgenes/index.html.erb
<h1>Listing mostsmallmobgenes</h1>

<table>
  <tr>
    <th>Mobspecie</th>
    <th>Mother</th>
    <th>Father</th>
    <th>Name</th>
    <th>Phys mod</th>
    <th>Int mod</th>
    <th>Prolificacy mod</th>
    <th>Longevity mod</th>
    <th>Cost mod</th>
    <th>Growth mod</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mostsmallmobgenes.each do |mostsmallmobgene| %>
  <tr>
    <td><%= mostsmallmobgene.mostsmallmobspecie.name %></td>
    <td><%= mostsmallmobgene.mothermobgene.name unless mostsmallmobgene.mothermobgene.nil? %></td>
    <td><%= mostsmallmobgene.fathermobgene.name unless mostsmallmobgene.fathermobgene.nil? %></td>
    <td><%= mostsmallmobgene.name %></td>
    <td><%= mostsmallmobgene.phys_mod %></td>
    <td><%= mostsmallmobgene.int_mod %></td>
    <td><%= mostsmallmobgene.prolificacy_mod %></td>
    <td><%= mostsmallmobgene.longevity_mod %></td>
    <td><%= mostsmallmobgene.cost_mod %></td>
    <td><%= mostsmallmobgene.growth_mod %></td>
    <td><%= link_to 'Show', mostsmallmobgene %></td>
    <td><%= link_to 'Edit', edit_mostsmallmobgene_path(mostsmallmobgene) %></td>
    <td><%= link_to 'Destroy', mostsmallmobgene, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mostsmallmobgene', new_mostsmallmobgene_path %>

app/views/mostsmallmobgenes/new.html.erb
<h1>New mostsmallmobgene</h1>

<%= render 'form' %>

<%= link_to 'Back', mostsmallmobgenes_path %>

app/views/mostsmallmobgenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mostsmallmobspecie:</b>
  <%= @mostsmallmobgene.mostsmallmobspecie.name %>
</p>

<p>
  <b>Mothermobgene:</b>
  <%= @mostsmallmobgene.mothermobgene.name unless @mostsmallmobgene.mothermobgene.nil? %>
</p>

<p>
  <b>Fathermobgene:</b>
  <%= @mostsmallmobgene.fathermobgene.name unless @mostsmallmobgene.fathermobgene.nil? %>
</p>

<p>
  <b>Name:</b>
  <%= @mostsmallmobgene.name %>
</p>

<p>
  <b>Phys mod:</b>
  <%= @mostsmallmobgene.phys_mod %>
</p>

<p>
  <b>Int mod:</b>
  <%= @mostsmallmobgene.int_mod %>
</p>

<p>
  <b>Prolificacy mod:</b>
  <%= @mostsmallmobgene.prolificacy_mod %>
</p>

<p>
  <b>Longevity mod:</b>
  <%= @mostsmallmobgene.longevity_mod %>
</p>

<p>
  <b>Cost mod:</b>
  <%= @mostsmallmobgene.cost_mod %>
</p>

<p>
  <b>Growth mod:</b>
  <%= @mostsmallmobgene.growth_mod %>
</p>


<%= link_to 'Edit', edit_mostsmallmobgene_path(@mostsmallmobgene) %> |
<%= link_to 'Back', mostsmallmobgenes_path %>